language: python
python:
  - "2.7"
#environment variables
env:
  global:
    - SECRET_KEY=1234567890

# command to install dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py syncdb

# command to run tests
script: python manage.py test
